### ISSUE TITLE
Resource averaged_perceptron_tagger not found.

### ISSUE THREAD

**Issue by mrmrn** [vivekkalyanarangan30/Text-Clustering-API#1]
hi, I installed requirements one by one, afterall it gaves me this error:
marn@mint18 ~/c/t/T/python> python CLAAS_public.py
Traceback (most recent call last):
  File "CLAAS_public.py", line 70, in <module>
    tagger = PerceptronTagger()
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/perceptron.py", line 140, in __init__
    AP_MODEL_LOC = 'file:'+str(find('taggers/averaged_perceptron_tagger/'+PICKLE))
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 673, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  Searched in:
    - '/home/marn/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/nltk_data'
    - '/usr/lib/nltk_data'
**********************************************************************

**Comment by vivekkalyanarangan30** [comment]
Like the error suggests, please download the `averaged_perceptron_tagger` by typing `nltk.download()` in the python console and looking for it! Closing as it's just an nltk dependency issue
